"""OpenSCAD parametric export with polyhedron() calls."""


def _hex_to_scad_color(hex_color: str) -> str:
    """Convert hex color to OpenSCAD color name or RGB."""
    h = hex_color.lstrip("#")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return f"[{r:.3f}, {g:.3f}, {b:.3f}]"


def export_openscad(
    meshes: list[dict],
    output_path: str,
    model_params,
) -> None:
    """Export meshes as a parametric OpenSCAD file.

    The .scad file includes:
    - Editable parameters at the top
    - polyhedron() calls for each mesh
    - Color assignments per feature type
    """
    lines = [
        "// Generated by topo-shadow-box",
        "// Open in OpenSCAD to render and customize",
        "",
        "// ============================================",
        "// Parameters (edit these to customize)",
        "// ============================================",
        f"model_width = {model_params.width_mm};",
        f"vertical_scale = {model_params.vertical_scale};",
        f"base_height = {model_params.base_height_mm};",
        f"model_shape = \"{model_params.shape}\";",
        "",
        "// ============================================",
        "// Meshes",
        "// ============================================",
    ]

    for mesh in meshes:
        name = mesh["name"]
        mtype = mesh["type"]
        color = _hex_to_scad_color(mesh["color"])
        verts = mesh["vertices"]
        faces = mesh["faces"]

        if not verts or not faces:
            continue

        name.replace(" ", "_").replace("-", "_")
        lines.append("")
        lines.append(f"// {name} ({mtype})")
        lines.append(f"color({color})")

        # Format vertices
        lines.append("polyhedron(")
        lines.append("  points = [")

        # Write vertices in chunks for readability
        for i, v in enumerate(verts):
            comma = "," if i < len(verts) - 1 else ""
            lines.append(f"    [{v[0]:.4f}, {v[1]:.4f}, {v[2]:.4f}]{comma}")

        lines.append("  ],")
        lines.append("  faces = [")

        for i, f in enumerate(faces):
            comma = "," if i < len(faces) - 1 else ""
            lines.append(f"    [{f[0]}, {f[1]}, {f[2]}]{comma}")

        lines.append("  ]")
        lines.append(");")

    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
