"""OpenSCAD parametric export with polyhedron() calls."""


def _hex_to_scad_color(hex_color: str) -> str:
    """Convert hex color to OpenSCAD color name or RGB."""
    h = hex_color.lstrip("#")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return f"[{r:.3f}, {g:.3f}, {b:.3f}]"


def export_openscad(
    meshes: list[dict],
    output_path: str,
    model_params,
    frame_params,
) -> None:
    """Export meshes as a parametric OpenSCAD file.

    The .scad file includes:
    - Editable parameters at the top
    - polyhedron() calls for each mesh
    - A parametric frame module
    - Color assignments per feature type
    """
    lines = [
        "// Generated by topo-shadow-box",
        "// Open in OpenSCAD to render and customize",
        "",
        "// ============================================",
        "// Parameters (edit these to customize)",
        "// ============================================",
        f"model_width = {model_params.width_mm};",
        f"vertical_scale = {model_params.vertical_scale};",
        f"base_height = {model_params.base_height_mm};",
        f"model_shape = \"{model_params.shape}\";",
        "",
        f"frame_width = {frame_params.frame_width_mm};",
        f"frame_depth = {frame_params.frame_depth_mm};",
        f"wall_thickness = {frame_params.wall_thickness_mm};",
        "",
        "// ============================================",
        "// Shadow Box Frame Module",
        "// ============================================",
        "module shadow_box_frame(w, h, fw, fd, wt) {",
        "    // Outer dimensions",
        "    ow = w + 2 * fw;",
        "    oh = h + 2 * fw;",
        "    translate([-fw, -fd, -fw])",
        "    difference() {",
        "        cube([ow, fd, oh]);",
        "        translate([fw, wt, fw])",
        "            cube([w, fd, h]);",
        "    }",
        "}",
        "",
        "// ============================================",
        "// Meshes",
        "// ============================================",
    ]

    for mesh in meshes:
        name = mesh["name"]
        mtype = mesh["type"]
        color = _hex_to_scad_color(mesh["color"])
        verts = mesh["vertices"]
        faces = mesh["faces"]

        if not verts or not faces:
            continue

        safe_name = name.replace(" ", "_").replace("-", "_")
        lines.append("")
        lines.append(f"// {name} ({mtype})")
        lines.append(f"color({color})")

        # Format vertices
        lines.append(f"polyhedron(")
        lines.append(f"  points = [")

        # Write vertices in chunks for readability
        for i, v in enumerate(verts):
            comma = "," if i < len(verts) - 1 else ""
            lines.append(f"    [{v[0]:.4f}, {v[1]:.4f}, {v[2]:.4f}]{comma}")

        lines.append(f"  ],")
        lines.append(f"  faces = [")

        for i, f in enumerate(faces):
            comma = "," if i < len(faces) - 1 else ""
            lines.append(f"    [{f[0]}, {f[1]}, {f[2]}]{comma}")

        lines.append(f"  ]")
        lines.append(f");")

    # Add frame instantiation at the end
    frame_mesh = next((m for m in meshes if m["type"] == "frame"), None)
    if not frame_mesh:
        # If frame wasn't generated as a mesh, add the parametric module call
        lines.extend([
            "",
            "// ============================================",
            "// Frame (using parametric module)",
            "// ============================================",
            "// Uncomment to use the parametric frame instead of mesh:",
            f"// color({_hex_to_scad_color('#8B4513')})",
            "// shadow_box_frame(model_width, model_width, frame_width, frame_depth, wall_thickness);",
        ])

    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
