package exporters

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/huslage/topo-shadow-box/internal/session"
)

func ExportOpenSCAD(s *session.Session, outputPath string) error {
	meshes, err := collectMeshes(s)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by topo-shadow-box\n")
	for i, m := range meshes {
		r, g, bl := hexToOpenSCADColor(m.Color)
		fmt.Fprintf(&b, "color([%.4f, %.4f, %.4f]) polyhedron(\n", r, g, bl)
		b.WriteString("  points=[\n")
		for vi, v := range m.Vertices {
			comma := ","
			if vi == len(m.Vertices)-1 {
				comma = ""
			}
			fmt.Fprintf(&b, "    [%.6f, %.6f, %.6f]%s\n", v[0], v[1], v[2], comma)
		}
		b.WriteString("  ],\n")
		b.WriteString("  faces=[\n")
		for fi, f := range m.Faces {
			comma := ","
			if fi == len(m.Faces)-1 {
				comma = ""
			}
			fmt.Fprintf(&b, "    [%d, %d, %d]%s\n", f[0], f[1], f[2], comma)
		}
		b.WriteString("  ]\n")
		b.WriteString(");\n")
		if i < len(meshes)-1 {
			b.WriteString("\n")
		}
	}

	if err := os.WriteFile(outputPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write openscad: %w", err)
	}
	return nil
}

func hexToOpenSCADColor(hex string) (float64, float64, float64) {
	if len(hex) != 7 || hex[0] != '#' {
		return 0.5, 0.5, 0.5
	}
	var r, g, b uint8
	_, err := fmt.Sscanf(hex[1:], "%02x%02x%02x", &r, &g, &b)
	if err != nil {
		return 0.5, 0.5, 0.5
	}
	return float64(r) / 255.0, float64(g) / 255.0, float64(b) / 255.0
}
